fixup! [open][neva_upstreamable][ozone][dnd] Migrate ozone changes for drag and drop
:Release Notes:
Explicitely require UI resources compiling ozone DND

:Detailed Notes:
Compilation is breaking in some cases, if ozone is compiled before UI resources:

| ../../git/src/ozone/ui/desktop_aura/drag_image_view.cc:15:10: fatal error: ui/resources/grit/ui_resources.h: No such file or directory
|  #include "ui/resources/grit/ui_resources.h"
|           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

This change explicitely requires the resources to be compiled before.

:Testing Performed:
Compilation is successful.

:QA Notes:
Test-cases: N/A (compilation fix)

:Issues Addressed:

Change-Id: I1b0ecd3541d1d131a3c5f88384090a0195cfd942
Reviewed-on: http://gpro.lge.com/245035