fixup! [open][neva_upstreamable][media] Reimplement buffered range for url media.
:Release Notes:
Fix qemux86 build failure

:Detaield Notes:
Previous patch caused a compilation error on qemux86 build:
| ../../git/src/media/blink/neva/webos/webos_mediaclient_stub.cc:108:49:
| error: non-member function 'media::Ranges<base::TimeDelta>
| media::GetBufferedTimeRanges()' cannot have cv-qualifier
|  Ranges<base::TimeDelta> GetBufferedTimeRanges() const {

:Testing Performed:
Check qemux86 build compilation

:QA Notes:
Test-cases: N/A

:Issues Addressed:

Change-Id: I47fe96aaec4b4c6f2b0e6a68bd93a7f073f60057
Originally-Reviewed-on: http://gpro.lge.com/c/webos-pro/chromium72/+/265525
Reviewed-on: http://gpro.lge.com/c/webosose/chromium72/+/265526
Tested-by: Lokesh Kumar Goel <lokeshkumar.goel@lge.com>
Reviewed-by: Lokesh Kumar Goel <lokeshkumar.goel@lge.com>